apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-agent
spec:
  selector:
    matchLabels:
      app: fleet-agent
  template:
    metadata:
      labels:
        app: fleet-agent
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{.Values.image.repository}}:{{.Values.image.tag}}
        name: fleet-agent
      serviceAccountName: fleet-agent
