kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: istio-installer
subjects:
- kind: ServiceAccount
  name: istio-installer
  namespace: {{ .Values.global.istioNamespace | default "istio-system" }}
roleRef:
  kind: ClusterRole
  name: istio-installer
  apiGroup: rbac.authorization.k8s.io
