apiVersion: batch/v1
kind: Job
metadata:
  name: istioctl-uninstaller
  namespace: {{ .Values.global.istioNamespace | default "istio-system" }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: istioctl-uninstaller
          image: brendarearden/istio-test:4.1.9
          env:
          - name: RELEASE_NAME
            value: {{ .Release.Name }}
          - name: ISTIO_NAMESPACE
            value: {{ .Values.global.istioNamespace | default "istio-system "}}
          command: ["/bin/sh","-c"]
          args: ["/usr/local/app/scripts/uninstall_istio_system.sh"]
          volumeMounts:
          - name: config-volume
            mountPath: /app/istio-base.yaml
            subPath: istio-base.yaml
          {{- if .Values.overlayFile }}
          - name: overlay-volume
            mountPath: /app/overlay-config.yaml
            subPath: overlay-config.yaml
          {{ end }}
      volumes:
        - name: config-volume
          configMap:
            name: istio-installer-base
        {{- if .Values.overlayFile }}
        - name: overlay-volume
          configMap:
            name: istio-installer-overlay
        {{ end }}
      serviceAccountName: istio-installer
      restartPolicy: OnFailure
