apiVersion: batch/v1
kind: Job
metadata:
  name: istioctl-installer
  namespace: {{ .Values.global.istioNamespace | default "istio-system" }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: istioctl-installer
          image: brendarearden/istio-test:4.1.6
          env:
          - name: RELEASE_NAME
            value: {{ .Release.Name }}
          {{- if .Values.revision }}
          - name: CANARY_REVISION
            value: {{ .Values.revision }}
          {{- end }}
          - name: ISTIO_NAMESPACE
            value: {{ .Values.global.istioNamespace | default "istio-system "}}
          - name: FORCE_INSTALL
            value: {{ .Values.forceInstall | default "false" | quote }}
          command: ["/bin/sh","-c"]
          args: ["/usr/local/app/scripts/run.sh"]
          volumeMounts:
          - name: config-volume
            mountPath: /app/istio-base.yaml
            subPath: istio-base.yaml
          {{- if .Values.overlayFile }}
          - name: overlay-volume
            mountPath: /app/overlay-config.yaml
            subPath: overlay-config.yaml
          {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: istio-installer-base
        {{- if .Values.overlayFile }}
        - name: overlay-volume
          configMap:
            name: istio-installer-overlay
        {{- end }}
      serviceAccountName: istio-installer
      restartPolicy: Never
