# Default values for logging-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: rancher/banzaicloud-logging-operator
  tag: 3.9.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

annotations: {}

## Deploy CRDs used by Logging Operator.
##
createCustomResource: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector:
  kubernetes.io/os: linux

tolerations:
  - key: cattle.io/os
    operator: "Equal"
    value: "linux"
    effect: NoSchedule

affinity: {}

http:
  # http listen port number
  port: 8080
  # Service definition for query http service
  service:
    type: ClusterIP
    clusterIP: None
    # Annotations to query http service
    annotations: {}
    # Labels to query http service
    labels: {}

rbac:
  enabled: true
  psp:
    enabled: true

## SecurityContext holds pod-level security attributes and common container settings.
## This defaults to non root user with uid 1000 and gid 2000.	*v1.PodSecurityContext	false
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
podSecurityContext: {}
#  runAsNonRoot: true
#  runAsUser: 1000
#  fsGroup: 2000
securityContext: {}
#  allowPrivilegeEscalation: false
#  readOnlyRootFilesystem: true
  # capabilities:
  #   drop: ["ALL"]

## Operator priorityClassName
##
priorityClassName: {}

monitoring:
  # Create a Prometheus Operator ServiceMonitor object
  serviceMonitor:
    enabled: false
    additionalLabels: {}
    metricRelabelings: []
    relabelings: []

disablePvc: true

additionalLoggingSources:
  rke:
    enabled: false
    fluentbit:
      mountPath: ""
      log_level: "info"
      mem_buffer_limit: "5MB"
  rke2:
    enabled: false
    fluentbit:
      mountPath: ""
  k3s:
    enabled: false
    fluentbit:
      mountPath: ""
    container_engine: "systemd"
  aks:
    enabled: false
    fluentbit:
      mountPath: ""
  eks:
    enabled: false
    fluentbit:
      mountPath: ""
  gke:
    enabled: false
    fluentbit:
      mountPath: ""

images:
  config_reloader:
    repository: rancher/jimmidyson-configmap-reload
    tag: v0.4.0
  fluentbit:
    repository: rancher/fluent-fluent-bit
    tag: 1.6.10
  fluentbit_debug:
    repository: rancher/fluent-fluent-bit
    tag: 1.6.10-debug
  fluentd:
    repository: rancher/banzaicloud-fluentd
    tag: v1.11.5-alpine-9

fluentbit:
  # This "mountPath" applies to the root Logging CR, which is always created when installing this
  # chart. If you would like to change the "mountPath" for vendor Logging CRs, such as RKE, use
  # the "mountPath" for your provider/vendor in "additionalLoggingSources".
  mountPath: ""
  # These "tolerations" apply to every Logging CR, including vendor Logging CRs enabled in
  # "additionalLoggingSources". Unlike "mountPath", changing "tolerations" affects every Logging CR
  # installed.
  tolerations:
    - key: node-role.kubernetes.io/controlplane
      value: "true"
      effect: NoSchedule
    - key: node-role.kubernetes.io/etcd
      value: "true"
      effect: NoExecute

global:
  cattle:
    systemDefaultRegistry: ""
