apiVersion: v1
appVersion: 1.7.0
description: Helm chart for installing istio components with the istioctl
name: rancher-istio
version: 1.7.000
icon: https://charts.rancher.io/assets/logos/istio.svg
keywords:
- networking
- infrastructure
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: istio-system
  catalog.cattle.io/release-name: rancher-istio
  catalog.cattle.io/ui-component: istio
  catalog.cattle.io/requires-gvr: monitoring.coreos.com.prometheus/v1
  catalog.cattle.io/auto-install: rancher-kiali-server-crd=1.22.001
