overlayFile: ""
tag: 1.7.1
installerVersion: 1.6.8-rancher1
forceInstall: false

istiocoredns:
    enabled: false
    image:
      repository: rancher/coredns-coredns
      tag: 1.6.2
    pluginImage:
      repository: rancher/istio-coredns-plugin
      tag: 0.2-istio-1.1

base:
    enabled: true

cni:
    enabled: false
    repository: rancher/istio-install-cni
    tag: 1.7.1

egressGateways:
    enabled: false
    type: NodePort

ingressGateways:
    enabled: true
    type: NodePort

istiodRemote:
    enabled: false

pilot:
    enabled: true
    repository: rancher/istio-pilot
    tag: 1.7.1

policy:
    enabled: true
    repository: rancher/istio-mixer
    tag: 1.7.1

telemetry:
    enabled: true
    repository: rancher/istio-mixer
    tag: 1.7.1

sidecarInjectorWebhook:
  enableNamespacesByDefault: false
  objectSelector:
    enabled: true
    autoInject: true
  rewriteAppHTTPProbe: true

global:
  cattle:
    systemDefaultRegistry: ""
  proxy:
    repository: rancher/istio-proxyv2
    tag: 1.7.1
  proxy_init:
    repository: rancher/istio-proxyv2
    tag: 1.7.1
  defaultPodDisruptionBudget:
    enabled: true

# this can be removed in 1.7 as it is default
meshConfig:
  enablePrometheusMerge: true

# Kiali subchart from rancher-kiali-server
kiali:
  enabled: true
  auth:
    strategy: anonymous
  deployment:
    ingress_enabled: false
    repository: rancher/kiali-kiali
    tag: v1.23.0
  external_services:
    prometheus:
      custom_metrics_url: "http://rancher-monitoring-prometheus.cattle-monitoring-system.svc:9090"
      url: "http://rancher-monitoring-prometheus.cattle-monitoring-system.svc:9090"
    tracing:
      enabled: false
