revision: "" # leave blank for no canary deployment, or set to given revision, eg: "1-7-2"
overlayFile: |
  apiVersion: install.istio.io/v1alpha1
  kind: IstioOperator
  spec:
    components:
      ingressGateways:
      - enabled: true
        name: istio-ingressgateway
        namespace: cattle-istio-system
      - enabled: true
        k8s:
          resources:
            requests:
              cpu: 200m
          service:
            ports:
            - name: tcp-citadel-grpc-tls
              port: 8060
              targetPort: 8060
            - name: tcp-dns
              port: 5353
          serviceAnnotations:
            cloud.google.com/load-balancer-type: internal
        name: ilb-gateway
        namespace: user-ingressgateway-ns
      - enabled: true
        k8s:
          resources:
            requests:
              cpu: 200m
          service:
            ports:
            - name: tcp-citadel-grpc-tls
              port: 8060
              targetPort: 8060
            - name: tcp-dns
              port: 5353
          serviceAnnotations:
            cloud.google.com/load-balancer-type: internal
        name: other-gateway
        namespace: cattle-istio-system
    values:
      gateways:
        istio-ingressgateway:
          name: other-gateway
          type: NodePort
        istio-ingressgateway:
          name: ilb-gateway
          type: NodePort
tag: 1.6.7
installerVersion: 0.1.5
forceInstall: false

# these addon values will be deprecated starting in 1.7.0
grafana:
  enabled: false

kiali:
  enabled: false

prometheus:
  enabled: false

tracing:
  enabled: false

istiocoredns:
    enabled: false
    image:
      repository: coredns/coredns
      tag: 1.6.2
    pluginImage: istio/coredns-plugin:0.2-istio-1.1

base:
    enabled: true

cni:
    enabled: false

egressGateways:
    enabled: false
    type: NodePort

ingressGateways:
    enabled: true
    type: NodePort

istiodRemote:
    enabled: false

pilot:
    enabled: true
    image: pilot

policy:
    enabled: true
    image: mixer

telemetry:
    enabled: true
    image: mixer

sidecarInjectorWebhook:
  enableNamespacesByDefault: false
  objectSelector:
    enabled: true
    autoInject: true
  rewriteAppHTTPProbe: true

global:
  istioNamespace: cattle-istio-system
  proxy:
    image: proxyv2
  proxy_init:
    image: proxyv2
