url: https://kiali.org/helm-charts/kiali-server-1.32.0.tgz
version: 1.32.100
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
