url: https://kiali.org/helm-charts/kiali-server-1.34.1.tgz
packageVersion: 00
releaseCandidateVersion: 01
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
