image:
  repository: rancher/fleet
  tag: v0.3.0-alpha8
  imagePullPolicy: IfNotPresent

agentImage:
  repository: rancher/fleet-agent
  tag: v0.3.0-alpha8
  imagePullPolicy: IfNotPresent

# For cluster registration the public URL of the Kubernetes API server must be set here
# Example: https://example.com:6443
apiServerURL: ""

# For cluster registration the pem encoded value of the CA of the Kubernetes API server must be set here
# If left empty it is assumed this Kubernetes API TLS is signed by a well known CA.
apiServerCA: ""

# The URL of the webhook reciever that will receive webhooks events from GitHub
# Refer to documentation on how to setup Ingress or a Service LoadBalancer.
webhookReceiverURL: ""

# All repo URLs that match the below prefixes will be assumed to be github and a
# webhook will be setup if webhookReceiverURL is also set
githubURLPrefix: https://github.com

# Whether you want to allow cluster upon registration to specify their labels.
ignoreClusterRegistrationLabels: false

bootstrap:
  # The namespace that will be autocreated and the local cluster will be registered in
  namespace: fleet-local
  # A repo to add at install time that will deploy to the local cluster. This allows
  # one to fully bootstrap fleet, it's configuration and all it's downstream clusters
  # in one shot.
  repo: ""
  secret: ""
  branch: master
  dirs: ""
