annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/experimental: "true"
  catalog.cattle.io/namespace: cattle-system
  catalog.cattle.io/release-name: rancher-webhook
apiVersion: v2
appVersion: 0.1.0-alpha7
description: ValidatingAdmissionWebhook for Rancher types
name: rancher-webhook
version: 0.1.0-alpha700
