annotations:
  catalog.cattle.io/auto-install: rancher-monitoring-crd=match
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: cattle-monitoring-system
  catalog.cattle.io/provides-gvr: monitoring.coreos.com.prometheus/v1
  catalog.cattle.io/release-name: rancher-monitoring
  catalog.cattle.io/ui-component: monitoring
apiVersion: v1
appVersion: 0.38.1
description: Modifies the upstream Prometheus Operator chart, which provides easy
  monitoring definitions for Kubernetes services and the deployment and management
  of Prometheus instances, and enables Prometheus Adapter on a default Prometheus
  instance.
home: https://github.com/coreos/prometheus-operator
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
keywords:
- operator
- prometheus
- monitoring
maintainers:
- name: vsliouniaev
- name: bismarck
- email: gianrubio@gmail.com
  name: gianrubio
name: rancher-monitoring
sources:
- https://github.com/coreos/kube-prometheus
- https://github.com/coreos/prometheus-operator
- https://coreos.com/operators/prometheus
version: 8.16.100
