# {{- $found := dict -}}
# {{- set $found "monitoring.kiali.io/v1alpha1/MonitoringDashboard" false -}}
# {{- range .Capabilities.APIVersions -}}
# {{- if hasKey $found (toString .) -}}
# 	{{- set $found (toString .) true -}}
# {{- end -}}
# {{- end -}}
# {{- range $_, $exists := $found -}}
# {{- if (eq $exists false) -}}
# 	{{- required "Required CRDs are missing. Please install the rancher-kiali-server-crd chart before installing this chart." "" -}}
# {{- end -}}
# {{- end -}}
