{{- if .Values.web_root_override }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali-console
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kiali-server.labels" . | nindent 4 }}
data:
  env.js: |
    window.WEB_ROOT='/api/v1/namespaces/{{ .Release.Namespace }}/services/http:rancher-istio-kiali:20001/proxy';
{{- end }}
