apiVersion: v1
version: 0.0.1
description: Installs the CRDs for backup-restore-operator.
name: backup-restore-operator-crd
type: application
annotations:
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/release-name: backup-restore-operator-crd
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: cattle-resources-system
