apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-webhook
spec:
  selector:
    matchLabels:
      app: rancher-webhook
  template:
    metadata:
      labels:
        app: rancher-webhook
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: rancher-webhook
        imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
        ports:
        - name: https
          containerPort: 9443
      serviceAccountName: rancher-webhook
